# Generated by Django 5.1.4 on 2024-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_recette_categorie_alter_categorie_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='favoris',
            field=models.BooleanField(default=False),
        ),
    ]
