# Generated by Django 5.1.4 on 2024-12-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_remove_recette_etapes_remove_recette_favoris_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes', to='recettes.categorie'),
        ),
    ]
