# Generated by Django 5.1.4 on 2024-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_alter_recette_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recette',
            name='temps_cuisson',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
