# Generated by Django 5.1.4 on 2024-12-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0008_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='note_moyenne',
            field=models.FloatField(default=0.0),
        ),
    ]
