# Generated by Django 5.1.4 on 2025-01-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0010_rename_user_note_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='visites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
